spring:
  application:
    name: service-discovery
  config:
    import: classpath:secrets.yml
  datasource:
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
